# Generated by Django 2.2.9 on 2022-09-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220915_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
