# Generated by Django 2.2.16 on 2022-10-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221024_1608'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_employee_user',
        ),
    ]
